env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-1-release-amd64
  install_script:
    - portsnap  --interactive fetch && portsnap extract
  script:
    - env BATCH=1 make -C net/socat
